# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, Cruel World!

tasks:
  default:
    cmds:
      - task -l
    silent: true

  run:
    cmds:
      - cargo run

  run-nix:
    cmds:
      - nix develop -c cargo run
