# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  run-nix:
    cmds:
      - nix develop -c cargo run --features bevy/dynamic_linking
